language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  matrix:
    - FLAKE8_VERSION=""
    - FLAKE8_VERSION="2.0"
    - FLAKE8_VERSION="2.1"

install:
  - if [[ -n "$FLAKE8_VERSION" ]]; then pip install flake8=="$FLAKE8_VERSION"; fi
script:
  - python setup.py test
